# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [5]:
# run initialize.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null = np.zeros(10)
print(null)

#### 4. How to find the memory size of any array (★☆☆)

In [44]:
# memory size = (size of the array) * (memory size of one array element in bytes)

size = null.size
itemsize = null.itemsize
memory_size = size * itemsize
print(memory_size, 'bytes')

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
 # run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [47]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [48]:
a_rev = a[::-1]
print(a_rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [49]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [50]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
# array with random values: .random.random((shape))

a = np.random.random((3,3,3))
print(a)

[[[0.21904258 0.15719109 0.04102073]
  [0.80653297 0.7925915  0.48111581]
  [0.06649047 0.32082641 0.87869526]]

 [[0.10419351 0.50582327 0.59586439]
  [0.98948231 0.89251379 0.38684509]
  [0.36654025 0.17222724 0.3658474 ]]

 [[0.98920715 0.54216659 0.40817416]
  [0.41413474 0.30559651 0.74486424]
  [0.44203754 0.86810665 0.05607105]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
# maximum(or min.): .max(array) (or .min(array)) / array.max() or array.min()

b = np.random.random((10,10))
print(np.min(b))
print(np.max(b))

0.00015267559688414423
0.9684107517311129


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
# mean value: .mean(array) / array.mean()

c = np.random.random(30)
print(np.mean(c))

0.5003494174576216


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [54]:
a = np.ones((4,4))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [55]:
# add boarder: .pad(array, pad_width=?, mode='constant', constant_values=?)

a = np.ones((2,2))
a = np.pad(a, pad_width=1, mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [56]:
# nan = not a number
# inf = infinity

print(0 * np.nan) # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan) # False
print(np.nan - np.nan) # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1) # False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
# diagonal matrix: .diag(올 숫자들, k=0)
# 내려보내고 싶은 만큼 숫자를 k에 할당

a = np.diag([1,2,3,4], k=-1)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
# 8X8 null matrix 생성 후 원하는 자리에 1을 채우기

x = np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
# .unravel_index(몇번째인지 원하는 index, (array 구조 shape))
# >>> 그 인덱스가 선형인덱스에서 몇번째인지 출력됨.

np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
# .tile(array, (반복할 행 수, 반복할 열 수))
# >>> array를 반복

np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [59]:
# normalize: (x-mean)/std

x = np.random.random((5,5))
x = (x-np.mean(x)) / (np.std(x))
print(x)

[[-0.97334214 -1.52399183 -0.34089036 -1.38450027  0.42487435]
 [-0.60339901 -0.14783372 -1.1800589  -0.88546473  0.21434204]
 [ 1.76581636  1.73573954 -0.53387256 -0.39808073 -0.79250107]
 [-1.22684716  0.91165944 -0.12899214  0.30249285  0.87881397]
 [ 0.02743253  1.36433609 -0.46287822  1.33704559  1.62010008]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
# matrix multiply: .dot(array,array) / array @ array

np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
x = np.arange(11)
x[(x>=3)&(x<=8)] *= -1
print(x)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1)) # 9
from numpy import *
print(sum(range(5),-1)) # 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [75]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [78]:
print(np.array(0) / np.array(0)) # nan
print(np.array(0) // np.array(0)) # 0
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-78-883639821ecf>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0)) # nan
<ipython-input-78-883639821ecf>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # 0


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
Z = np.array([32.11, 51.5, 0.112])
print(np.round(Z,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [86]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 3 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
 # Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# equivalent way, with a context manager
with np.errstate(all='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [88]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # False

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [37]:
# 달 사이의 모든 날짜 구하기: 
# .arange('시작달', '끝달', dtype='datetime64[D]')

a = np.arange('2016-07', '2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
Z = np.random.uniform(0,10,10)

print(Z-Z%1)
print(Z//1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[6. 0. 2. 5. 0. 1. 8. 3. 4. 0.]
[6. 0. 2. 5. 0. 1. 8. 3. 4. 0.]
[6. 0. 2. 5. 0. 1. 8. 3. 4. 0.]
[6 0 2 5 0 1 8 3 4 0]
[6. 0. 2. 5. 0. 1. 8. 3. 4. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [41]:
a = np.tile(np.arange(5), (5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [44]:
# .fromiter(iterableData, dtype, count=-1)

def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=int, count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [47]:
# .linspace(start, end, num, endpoint=?, retstep=?)

a = np.linspace(0,1,11, endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [49]:
a = np.random.random(10)
a.sort()
print(a)

[0.0273011  0.03018396 0.04825014 0.17408943 0.23533258 0.34604218
 0.5536145  0.72188829 0.74801001 0.96313762]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [3]:
# np.add.reduce

a = np.arange(5)
np.add.reduce(a)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
# check equal: .allclose(A,B) / .array_equal(A,B)
# >>> True or False

a = np.random.randint(0,10,5)
b = np.random.randint(0,10,5)

print(np.allclose(a,b))
print(np.array_equal(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [53]:
# array.flags.writeable = False : array 변경 불가능

a = np.zeros(5)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [57]:
# cartesian > polar: (sqrt(x^2+y^2), arctan2(y,x))

a = np.random.random((3,2))
x,y = a[:,0],a[:,1]
R = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print(R)
print(T)

[0.8620376  1.14597309 1.02981079]
[1.18014132 0.7984229  1.01503581]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
# .argmax(): 최대값의 index
# array[array.argmax()]: 최대값의 index에 위치한 값 = 최대값

a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.68295919 0.75269951 0.44540239 0.11753698 0.66071011 0.1733096
 0.         0.1608895  0.57421791 0.36154208]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [9]:
a = np.zeros((5,5), [('x',float),('y',float)])

x1 = np.linspace(0,1,5)
y1 = np.linspace(0,1,5)
a['x'],a['y'] = np.meshgrid(x1, y1)

print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [13]:
# .substract.outer(x,y) = x-y
# .linalg.det(matrix) : determinant 계산값

x = np.arange(10)
y = x+0.5
C = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(C))

33961.93294480225


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [14]:
# .iinfo(): int에 대한 정보
# .finfo(): float에 대한 정보
# .eps: 표현 가능한 가장 작은 값

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [16]:
# .set_printoptions(): print 옵션 설정
# threshold: 요약을 하는 배열 요소의 총 수

np.set_printoptions(threshold=float('inf'))

a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [17]:
a = np.arange(100)
b = np.random.uniform(0,100)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

85.01963079948746
85


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [75]:
Z = np.zeros(10,[('position',[('x',float,1),
                             ('y', float,1)]),
                ('color', [('r',float,1),
                         ('g',float,1),
                         ('b',float,1)]) ])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-75-6f9bae43b5b8>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10,[('position',[('x',float,1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [18]:
a = np.random.random((10,2))
x,y = np.atleast_2d(a[:,0],a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.06554441 0.7020177  0.59421477 0.06760744 0.78206395
  0.98419397 0.60769429 0.92931527 0.28636347]
 [0.06554441 0.         0.68431464 0.56570758 0.01605789 0.73474707
  0.96608929 0.56039598 0.8983949  0.23009981]
 [0.7020177  0.68431464 0.         0.15914723 0.69993875 0.3873764
  0.28223161 0.35216624 0.28052123 0.5363707 ]
 [0.59421477 0.56570758 0.15914723 0.         0.58049218 0.29526952
  0.4156261  0.20613198 0.33551288 0.39120214]
 [0.06760744 0.01605789 0.69993875 0.58049218 0.         0.7462019
  0.98163467 0.5719843  0.91275934 0.23953068]
 [0.78206395 0.73474707 0.3873764  0.29526952 0.7462019  0.
  0.49739271 0.17446208 0.30409389 0.51044633]
 [0.98419397 0.96608929 0.28223161 0.4156261  0.98163467 0.49739271
  0.         0.55426371 0.2084092  0.8066899 ]
 [0.60769429 0.56039598 0.35216624 0.20613198 0.5719843  0.17446208
  0.55426371 0.         0.40168498 0.33773034]
 [0.92931527 0.8983949  0.28052123 0.33551288 0.91275934 0.30409389
  0.2084092  0.4016849

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [20]:
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [24]:
# .genfromtxt(변수, delimiter='구분자', dtype=np.dtype): missing value 수정해서 보여줌 

from io import StringIO

a = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
 ''')
b = np.genfromtxt(a, delimiter=',', dtype=np.int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [25]:
# .ndenumerate(array) / .ndindex(): 다차원 index 반환

z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [85]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d-mu)**2 / (2.0*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [27]:
# .put(array, n, k): array에서 n개를 k로 replace

n = 5
p = 5
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n),p,replace=False),1)
print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [30]:
# array.mean(axis=0 or 1, keepdims=True or False)
# keepdims=True : 차원 그대로 유지

x = np.random.rand(2,5)
print(x)
y = x-x.mean(axis=1, keepdims=True)
print(y)

[[0.45348962 0.29264483 0.00401772 0.63485563 0.52640016]
 [0.53958103 0.7680113  0.5663191  0.19357817 0.68487947]]
[[ 0.07120802 -0.08963676 -0.37826387  0.25257404  0.14411856]
 [-0.01089278  0.21753748  0.01584529 -0.35689564  0.13440565]]


#### 59. How to sort an array by the nth column? (★★☆)

In [89]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()]) # 행 첫번째 성분을 기준으로 정렬.

[[1 6 4]
 [1 5 3]
 [6 7 1]]
[[1 5 3]
 [1 6 4]
 [6 7 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [34]:
# (~array.any(axis=0 or 1)).any() : null인 column 또는 row가 있는가.

a = np.random.randint(0,2,(3,10))
print(a)
print((~a.any(axis=0)).any())

[[0 0 1 0 1 1 1 1 0 1]
 [0 0 1 0 0 0 0 0 1 1]
 [1 0 0 0 1 0 1 1 0 1]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [3]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z[np.abs(Z-z).argmin()]
print(m)

0.5322849826929394


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [93]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for x,y,z in it:
    z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [95]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', 'no name')

a = NamedArray(np.arange(10), "range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [97]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

np.add.at(a, b, 1)
print(a)

[4. 2. 2. 3. 3. 5. 2. 2. 4. 3.]
[7. 3. 3. 5. 5. 9. 3. 3. 7. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [108]:
X = [1,2,3,4,5]
I = [2,5,8,1,2]
F = np.bincount(I,X)
print(F)

[0. 4. 6. 0. 0. 2. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [109]:
w,h = 256, 256
a = np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors = np.unique(a.reshape(-1,3),axis=0)
n=len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [110]:
a = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

3


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [111]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.53377707 0.52648405 0.52392832 0.35759414 0.49073779 0.54613048
 0.56418353 0.61104018 0.30533004 0.57578841]


#### 69. How to get the diagonal of a dot product? (★★★)

In [113]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))

array([1.71530919, 1.04369252, 1.90931637, 1.44297717, 0.55763686])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [114]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*b)
c[::b+1]=a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [115]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [117]:
a = np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [118]:
a = np.random.randint(0,100,(10,3))
b = np.roll(a.repeat(2,axis=1),-1, axis=1)
b = b.reshape(len(b)*3,2)
b = np.sort(b, axis=1)
c = b.view(dtype=[('p0',b.dtype),('p1',b.dtype)])
c = np.unique(c)
print(c)

[( 1, 31) ( 1, 95) ( 2,  7) ( 2, 45) ( 7, 20) ( 7, 45) ( 7, 99) (13, 26)
 (13, 86) (14, 62) (14, 79) (16, 19) (16, 83) (18, 54) (18, 62) (19, 83)
 (20, 99) (26, 86) (29, 46) (29, 63) (31, 95) (46, 63) (54, 62) (56, 84)
 (56, 86) (62, 79) (68, 86) (68, 88) (84, 86) (86, 88)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [119]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [120]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [121]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
b = rolling(np.arange(10), 3)
print(b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [127]:
a = np.random.randint(0,2,100)
print(np.logical_not(a, out=a))

a = np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))

[0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1
 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 0]
[ 0.6154064  -0.51044713 -0.38694842  0.56058943  0.82345731 -0.66699931
 -0.37583365  0.26046935 -0.33938996 -0.48883118 -0.74463259  0.75059733
  0.92689818  0.28780334  0.74482766  0.81328123  0.19271489 -0.10141081
  0.04177486 -0.79910531  0.38487819 -0.55456368 -0.78828138  0.84291008
 -0.70374309 -0.7414349   0.07412268 -0.53921437  0.66192372 -0.85384994
 -0.63407611 -0.13899581  0.07334348 -0.45446869 -0.52190285  0.60118354
  0.99083636  0.30931443  0.37285034  0.45806578  0.39998343  0.13635754
 -0.71012403  0.2723814   0.43633204  0.29526277 -0.36672053 -0.3184108
 -0.77595919 -0.80978447 -0.99250804 -0.43688016  0.59561909 -0.59264101
  0.5202098   0.94832185  0.20682795  0.13960771  0.43525209 -0.55253868
 -0.58508013 -0.47157329 -0.6147567   0.97744673  0.86231536  0.168

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [128]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.54327973  7.0317251   5.02293835  0.16934051  0.21706115  5.60382047
  0.37032943 11.92714938  3.3922194   6.64475039]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [129]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.9810692   4.80669189  3.50898307  2.95255532  7.74290504  6.23046542
   7.15145378  2.43004793  6.79539647  6.25967395]
 [ 5.74125129  3.02530274  2.66580001  4.54410897  6.10444865  7.84486909
   8.70504369  1.44489559  7.46726557  7.35533396]
 [ 4.61490249 11.50449672  2.76244545  1.60327216  9.89122867  4.70056208
   4.26337517  2.76651914  5.90676025  6.60845344]
 [ 5.48521569  3.35173888  3.13782401  4.09659852  6.53961358  7.71250433
   8.60778186  1.92473954  7.68635335  7.44876015]
 [ 6.24493084 11.93597296  8.30412964  4.03834626  7.84646551  8.04988334
   8.03154322  7.94453585 12.26229278 12.19794454]
 [ 8.52989672  1.11234925  5.49713547 11.28649214  0.33768358  8.40028561
   8.65102929  6.69223475  2.34081246  4.15123928]
 [ 5.28759024 12.17719507  2.48221571  1.02100143 10.49372896  5.32985834
   4.87258742  2.4304903   6.20162241  7.05757806]
 [ 6.61516229  0.66351194  5.42041222 10.07483476  0.97110745  6.39762605
   6.65135649  6.43020927  0.84777791  2.35120965]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [131]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 7 3 4 7 8 6 3 4 0]
 [6 6 2 9 5 5 2 5 1 3]
 [7 7 1 9 5 2 6 8 8 0]
 [2 8 6 5 2 1 6 2 8 8]
 [4 6 0 4 5 6 2 7 9 0]
 [6 2 2 9 5 6 0 0 4 1]
 [0 3 0 0 6 9 8 9 3 9]
 [5 4 7 5 8 7 6 5 9 5]
 [0 9 3 7 1 6 2 5 8 5]
 [2 3 9 1 2 8 2 4 4 7]]
[[0 0 0 0 0]
 [0 2 7 3 4]
 [0 6 6 2 9]
 [0 7 7 1 9]
 [0 2 8 6 5]]


<ipython-input-131-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [132]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [133]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [134]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [135]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 4]
   [4 0 0]
   [1 3 3]]

  [[2 4 1]
   [0 0 1]
   [3 3 1]]

  [[4 1 1]
   [0 1 1]
   [3 1 0]]

  [[1 1 2]
   [1 1 4]
   [1 0 0]]

  [[1 2 4]
   [1 4 4]
   [0 0 0]]

  [[2 4 4]
   [4 4 0]
   [0 0 2]]

  [[4 4 4]
   [4 0 0]
   [0 2 1]]

  [[4 4 1]
   [0 0 0]
   [2 1 0]]]


 [[[4 0 0]
   [1 3 3]
   [4 4 0]]

  [[0 0 1]
   [3 3 1]
   [4 0 0]]

  [[0 1 1]
   [3 1 0]
   [0 0 0]]

  [[1 1 4]
   [1 0 0]
   [0 0 2]]

  [[1 4 4]
   [0 0 0]
   [0 2 0]]

  [[4 4 0]
   [0 0 2]
   [2 0 4]]

  [[4 0 0]
   [0 2 1]
   [0 4 1]]

  [[0 0 0]
   [2 1 0]
   [4 1 3]]]


 [[[1 3 3]
   [4 4 0]
   [0 4 0]]

  [[3 3 1]
   [4 0 0]
   [4 0 4]]

  [[3 1 0]
   [0 0 0]
   [0 4 0]]

  [[1 0 0]
   [0 0 2]
   [4 0 0]]

  [[0 0 0]
   [0 2 0]
   [0 0 0]]

  [[0 0 2]
   [2 0 4]
   [0 0 1]]

  [[0 2 1]
   [0 4 1]
   [0 1 4]]

  [[2 1 0]
   [4 1 3]
   [1 4 4]]]


 [[[4 4 0]
   [0 4 0]
   [4 3 0]]

  [[4 0 0]
   [4 0 4]
   [3 0 2]]

  [[0 0 0]
   [0 4 0]
   [0 2 3]]

  [[0 0 2]
   [4 0 0]
   [2 3 0]]

  [[0 2 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [136]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 13 12  5 11]
 [13  9 12  2  9]
 [12 12  7 42  8]
 [ 5  2 42  6 15]
 [11  9  8 15  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [137]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [138]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [139]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [140]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [141]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [143]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [144]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.94 s ± 549 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
737 ms ± 193 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
284 ms ± 28.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [145]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [153]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[1 4 0]
 [2 1 0]
 [0 1 2]
 [0 1 0]
 [1 0 1]
 [1 4 0]
 [1 4 4]
 [3 2 4]
 [4 0 2]
 [4 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [150]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [154]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [156]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.52801724, 0.87167925, 0.1238678 , 0.05272028, 0.88323015,
        0.32633958, 0.64686341, 0.64472597, 0.8023246 , 0.14027386],
       [0.54257641, 0.89571431, 0.12728324, 0.05417395, 0.9075837 ,
        0.33533783, 0.66469956, 0.66250318, 0.82444732, 0.14414167],
       [0.39942666, 0.65939501, 0.09370168, 0.03988106, 0.66813286,
        0.24686453, 0.48932965, 0.48771275, 0.60693063, 0.10611229],
       [0.19848137, 0.32766372, 0.04656183, 0.01981752, 0.3320057 ,
        0.12267086, 0.24315558, 0.24235211, 0.30159335, 0.05272886],
       [0.10660373, 0.17598716, 0.02500822, 0.01064393, 0.17831923,
        0.06588614, 0.1305981 , 0.13016657, 0.16198485, 0.02832051],
       [0.13296706, 0.21950917, 0.0311928 , 0.0132762 , 0.22241796,
        0.08217992, 0.1628953 , 0.16235704, 0.20204405, 0.03532423],
       [0.22607846, 0.37322248, 0.05303585, 0.02257298, 0.37816817,
        0.13972716, 0.27696423, 0.27604905, 0.34352725, 0.06006035],
       [0.06527207, 0.10775464, 0.0153122

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [159]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [160]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [161]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17390569  0.20919192]
